### ISSUE TITLE
[BUG] Error messages shouldn't be blockers

### ISSUE THREAD

**Issue by brunoamuniz** [Flutter-Vision/FlutterVision#10]
## **Describe the bug**
When an error show's up, the user need to refresh the page to use the system again

right behavior should be to have a "close" button (X) or when he clicks outside the error, he could keep using the application

<img width="1376" alt="Screen Shot 2022-03-18 at 09 51 51" src="https://user-images.githubusercontent.com/3296036/159006758-8047de7d-e850-495b-8f58-d499c35d1295.png">

**Comment by reness0** [comment]
@all-contributors please add @brunoamuniz for bug and test

**Comment by brunoamuniz** [comment]
message was shown to me but after clicking the X it didnt close the message... it still running

<img width="927" alt="Screen Shot 2022-04-19 at 16 04 47" src="https://user-images.githubusercontent.com/3296036/164077289-6708e8d0-b74b-46ee-9a6a-b2e9d1d05669.png">
<img width="895" alt="Screen Shot 2022-04-19 at 16 04 42" src="https://user-images.githubusercontent.com/3296036/164077313-549570e2-395c-4579-a464-bb51cebe0f01.png">
