### ISSUE TITLE
"Frames" are coming as "Image Button" or "Button", without icons, texts, etc.

### ISSUE THREAD

**Issue by pattrickx** [Flutter-Vision/FlutterVision#17]
Frames should come as containers, with its respective components. In the second image, to ensure a Button with text and icon, it will be interesting to import as Image Button.

Project Key: ppI115bKoQsrG5hPObPbLo

![image](https://user-images.githubusercontent.com/32752004/159275850-dca78718-9d4c-4b3e-8b58-f6ae36f889de.png)

![image](https://user-images.githubusercontent.com/32752004/159275879-dc40653e-27ad-4677-abf6-8ce6046859e2.png)

**Comment by pattrickx** [comment]
This will be solved in a new AI training, with a dataset update

**Comment by reness0** [comment]
@all-contributors please add @pattrickx for code and maintenance

**Comment by reness0** [comment]
@all-contributors please add @pattrickx for code and maintenance

**Comment by pattrickx** [comment]
Simplified step-by-step to update our AI model

- [ ] Add new screenshots to the existing dataset.
- [ ] Define which components should be added to the initial set.
- [ ] Define what each component is, shapes and what is contained by each, with example images.
- [ ] Update image tagging code with the new information.
- [ ] Separate data to be marked by our developers, or seek people willing to receive to do this work.
- [ ] Pass the information on how the markings should be made and do a supervised test, with data that were previously marked, within the defined pattern.
- [ ] Send data packet to markers.
- [ ] Check and correct incorrect tags, and assign tags to future packages.
- [ ] Start training and testing with new dataset.
- [ ] Check the quality of the result of the new models.
- [ ] Replace current production model

**Comment by pattrickx** [comment]
these issues will be resolved by issue #87
