### ISSUE TITLE
Implement the screen padding in the frontEnd

### ISSUE THREAD

**Issue by mateuslimax22** [Flutter-Vision/FlutterVision#18]

**Comment by reness0** [comment]
@all-contributors please add @mateuslimax22 for code, bug and test

**Comment by brunoamuniz** [comment]
working properly
<img width="906" alt="Screen Shot 2022-03-23 at 15 57 41" src="https://user-images.githubusercontent.com/3296036/159775377-a87ba7f1-761a-4ce7-9f23-45520533a194.png">
<img width="912" alt="Screen Shot 2022-03-23 at 15 57 31" src="https://user-images.githubusercontent.com/3296036/159775386-e0dd02d2-e19c-45b8-a7ff-d98510640788.png">
