### ISSUE TITLE
Update the component names for Flutter

### ISSUE THREAD

**Issue by WixeI** [Flutter-Vision/FlutterVision#24]

**Comment by teras** [comment]
Supported on the backend with commit a33ab6540fe7afd44f261fc0b89125eecce7755a

**Comment by brunoamuniz** [comment]
Hint of components in FV doesn't match the name in the Properties Tab

<img width="666" alt="Screen Shot 2022-05-09 at 15 29 16" src="https://user-images.githubusercontent.com/3296036/167477424-da408ce5-0465-4244-ae46-20ddd3ae69bf.png">
<img width="656" alt="Screen Shot 2022-05-09 at 15 29 28" src="https://user-images.githubusercontent.com/3296036/167477435-582ed1f3-db54-4596-be50-e6bd964f56b6.png">

**Comment by WixeI** [comment]
> Hint of components in FV doesn't match the name in the Properties Tab
> 
> <img alt="Screen Shot 2022-05-09 at 15 29 16" width="666" src="https://user-images.githubusercontent.com/3296036/167477424-da408ce5-0465-4244-ae46-20ddd3ae69bf.png">
> 
> <img alt="Screen Shot 2022-05-09 at 15 29 28" width="656" src="https://user-images.githubusercontent.com/3296036/167477435-582ed1f3-db54-4596-be50-e6bd964f56b6.png">

Fixed
