### ISSUE TITLE
[FEATURE] Understand how to build "rounded borders" in Flutter components

### ISSUE THREAD

**Issue by reness0** [Flutter-Vision/FlutterVision#31]

**Comment by pattrickx** [comment]
@reness0 now the AI ​​sends this information to the edge and lines of the components, strokeAlign will have one of these 3 options [ 'outside','inside', 'center']

'cornerRadius': 0,
'strokeWeight': 1.0,
'strokeAlign': 'outside'

**Comment by reness0** [comment]
can we have a class called border and then the json would look like: 

```javascript
'border': {
'cornerRadius': 0,
'strokeWeight': 1.0,
'strokeAlign': 'outside'
} 
```

what do u think @teras?

**Comment by rene-kt** [comment]
put as: 
```javascript
'style': {
  'border' : {
    'cornerRadius': 0,
    'strokeWeight': 1.0,
    'strokeAlign': 'outside'
  }
} 
```
@pattrickx

**Comment by brunoamuniz** [comment]
I just placed different corners and it didn't work, is it right?!

<img width="824" alt="Screen Shot 2022-04-04 at 13 24 14" src="https://user-images.githubusercontent.com/3296036/161588796-d3584fa2-8120-4255-b1e9-8256b8353d31.png">

**Comment by rene-kt** [comment]
@pattrickx can u retrieve the border radius for specific sides? e.g only for top, bottom, left, right

**Comment by brunoamuniz** [comment]
this is what we have in figma!

we can specify for each corner the radius or set one info for every corner

<img width="247" alt="Screen Shot 2022-04-04 at 15 20 11" src="https://user-images.githubusercontent.com/3296036/161606977-84fdd94c-9e68-46a3-8b2c-239d7955c77c.png">
<img width="247" alt="Screen Shot 2022-04-04 at 15 20 22" src="https://user-images.githubusercontent.com/3296036/161606979-39db3334-3e26-4dc9-8fbd-400f0764b175.png">

**Comment by teras** [comment]
Is there specific care for Flutter to support different style per corner? 
If not, we have to skip this feature.

**Comment by brunoamuniz** [comment]
borders of containers should be contemplated 

![Screen Shot 2022-04-06 at 12 59 32](https://user-images.githubusercontent.com/3296036/162017517-8ef58446-770a-4733-8270-eda7f1d452bf.png)

**Comment by brunoamuniz** [comment]
it improved but still getting the wrong information

<img width="1173" alt="Screen Shot 2022-04-07 at 13 16 48" src="https://user-images.githubusercontent.com/3296036/162251124-69c4a41b-65b3-4dd1-ae6c-71724973c60d.png">

**Comment by rene-kt** [comment]
@pattrickx can we check that later? im just passsing information, maybe it might be a missunderstood in the json

**Comment by brunoamuniz** [comment]
Still not working...

information is in FV web but not reflecting in the Flutter code

https://www.figma.com/file/Sx7HqLk6EAQDBwnUhGlKqL/KCBank?node-id=0%3A1

<img width="932" alt="Screen Shot 2022-04-12 at 11 24 46" src="https://user-images.githubusercontent.com/3296036/162984715-cbb8b098-c57a-41f6-ab4b-11cdadc20f55.png">

**Comment by pattrickx** [comment]
@reness0 please look at this issue, the information is being shown on the front-end but it is not showing up in the export

**Comment by rene-kt** [comment]
ok, perfect, thx @pattrickx
