### ISSUE TITLE
[FEATURE] Support resizing property "Hug Contents"

### ISSUE THREAD

**Issue by reness0** [Flutter-Vision/FlutterVision#32]

**Comment by brunoamuniz** [comment]
front is not getting the right information from figma

https://www.figma.com/file/Sx7HqLk6EAQDBwnUhGlKqL/KCBank?node-id=353%3A2

<img width="583" alt="Screen Shot 2022-04-22 at 10 36 31" src="https://user-images.githubusercontent.com/3296036/164725342-c4caf9f0-6fbc-4051-9889-990f82f6ba40.png">

<img width="721" alt="Screen Shot 2022-04-22 at 10 36 05" src="https://user-images.githubusercontent.com/3296036/164725368-fd56b69f-cc90-4ef9-b694-6f777ad01f4f.png">

**Comment by brunoamuniz** [comment]
implementation in Flutter seems to be ok
