### ISSUE TITLE
[BUG] Retrieving the fill information incorretcly

### ISSUE THREAD

**Issue by reness0** [Flutter-Vision/FlutterVision#34]

**Comment by reness0** [comment]
Discussion about this issue: https://gitlab.com/knowcodeapp/flutter-vision/-/issues/25

**Comment by brunoamuniz** [comment]
added the FillContainer information and it stopped showing up

<img width="990" alt="Screen Shot 2022-03-30 at 10 32 52" src="https://user-images.githubusercontent.com/3296036/160846771-54a86e6f-dbc1-40d3-9e8c-c4e44ca2e21e.png">

**Comment by rene-kt** [comment]
@brunoamuniz can u test it again? i just tested here with the new version and it looks its working (but still missing the fill implementation #36

**Comment by rene-kt** [comment]
this issue was already fixed and closed by @pattrickx, for the backend and template part it is the issue #36 @brunoamuniz 

can i close or move to somewhere else than In Progress?
