### ISSUE TITLE
Implement background image for the screens AI

### ISSUE THREAD

**Issue by reness0** [Flutter-Vision/FlutterVision#35]
We need to retrieve this info from figma @pattrickx

**Comment by pattrickx** [comment]
this kind of information cannot be retrieved from figma because it has no parameter to define whether some component is a background image

**Comment by brunoamuniz** [comment]
tested with example 65 from the spreadsheet and it added the wrong image background.

FV front and flutter seems to be ok

image added as background

![iPhoneProX_screen_2-73x686](https://user-images.githubusercontent.com/3296036/167425535-abeb39ff-67f4-48f8-b4f6-d590e3397d45.png)
