### ISSUE TITLE
[BUG] Loading UI is completely broken for the user =(

### ISSUE THREAD

**Issue by brunoamuniz** [Flutter-Vision/FlutterVision#4]
## **Describe the bug**
the screen after you input the information of Figma file is broken for the user.

I attached an image

## **To Reproduce**
- add the figma token and project key
- hit the button

<img width="1420" alt="Screen Shot 2022-03-16 at 16 04 54" src="https://user-images.githubusercontent.com/3296036/158669076-c54f85a1-62cb-410d-933f-240d244e8243.png">

**Comment by reness0** [comment]
@all-contributors please add @brunoamuniz for bug

**Comment by WixeI** [comment]
Fixed. We don't have the "To Test" tag here yet, but this is currently in this state.
Go check at https://backtest.knowcode.app/

**Comment by brunoamuniz** [comment]
it is working!! Kaique needs to approve it too

**Comment by reness0** [comment]
@all-contributors please add @WixeI for code and maintenance
