### ISSUE TITLE
[BUG] Error on Flutter when screen name has a number as first character

### ISSUE THREAD

**Issue by SabrinaSioli** [Flutter-Vision/FlutterVision#44]
Hello guys,
we have some problems with numbers when they are the first character in screen names or component names.
It is returning an error in Flutter.
we should replace number from screen name and component names (just at the beginning)

**Comment by brunoamuniz** [comment]
in this example still happens the issue 

https://www.figma.com/file/SF15TM62dQGrUVZEzTNZwU/Untitled?node-id=1%3A2

**Comment by brunoamuniz** [comment]
still not working https://www.figma.com/file/SF15TM62dQGrUVZEzTNZwU/Untitled?node-id=1%3A2

**Comment by brunoamuniz** [comment]
still same error

https://www.figma.com/file/SF15TM62dQGrUVZEzTNZwU/Untitled?node-id=0%3A1

<img width="966" alt="Screen Shot 2022-03-29 at 08 15 14" src="https://user-images.githubusercontent.com/3296036/160599531-a38a13ae-c96b-4d38-9a36-3f119007e31f.png">
