### ISSUE TITLE
Implement icons inside other components (e.g Buttons, EditTexts)

### ISSUE THREAD

**Issue by SabrinaSioli** [Flutter-Vision/FlutterVision#46]

**Comment by teras** [comment]
We are going to have a double approach:

* Test if we can use the AI to find the actual name of the icon, from a list of 2K icons from here https://api.flutter.dev/flutter/material/Icons-class.html
* See how to implement "custom icons', i.e. icons that we have the SVG paths. The paths will be extracted by Figma input and used as SVG files on Flutter.
