### ISSUE TITLE
RadioButton clickable area is really small

### ISSUE THREAD

**Issue by mateuslimax22** [Flutter-Vision/FlutterVision#49]
FileName??
![image](https://user-images.githubusercontent.com/38704964/159517820-712b21cc-9075-4bd1-be2c-3361873e4ae5.png)
Test if the "Group Name" properties appear in the radio button components and create multiple radio buttons with the same group name.

**Comment by reness0** [comment]
@all-contributors please add @mateuslimax22 for code, bug and maintenance

**Comment by kaiquemancoso** [comment]
@reness0 I was checking this issue and it's working on front-end and back-end. But it looks a little strange on the output, take a look:

<img width="392" alt="Screen Shot 2022-03-30 at 10 23 42" src="https://user-images.githubusercontent.com/71526720/160845519-484cbaf6-e3de-48d0-af02-6452031c0e94.png">

I'm not able to click on the RadioButton, only in the grey space before the component.

**Comment by kaiquemancoso** [comment]
It didn't work it

<img width="260" alt="Screen Shot 2022-04-06 at 14 10 12" src="https://user-images.githubusercontent.com/71526720/162030193-4cad222e-fa2f-4e48-b252-09adfbc5e1cd.png">
