### ISSUE TITLE
[BUG] Align text correctly following Figma info

### ISSUE THREAD

**Issue by reness0** [Flutter-Vision/FlutterVision#51]
It's necessary the data arrive from Figma, so this [issue](https://github.com/orgs/Flutter-Vision/projects/1#card-79627264) should be done first

**Comment by brunoamuniz** [comment]
new test made for this issue

<img width="714" alt="Screen Shot 2022-03-29 at 13 58 39" src="https://user-images.githubusercontent.com/3296036/160665969-34e847be-e14d-4dbe-9def-0b4d45bd9b5a.png">

**Comment by brunoamuniz** [comment]
still wrong the information. It is not getting the info properly from Figma

<img width="743" alt="Screen Shot 2022-04-11 at 15 11 58" src="https://user-images.githubusercontent.com/3296036/162802995-d634eaea-9681-42b1-9af2-111dcfb8abe4.png">

**Comment by rene-kt** [comment]
@pattrickx take a look on this, pls

**Comment by pattrickx** [comment]
I'm already working on it in issue #57
