### ISSUE TITLE
[BUG] FV not export when using screenshots

### ISSUE THREAD

**Issue by kaiquemancoso** [Flutter-Vision/FlutterVision#56]
When clicking on export, after uploading screenshots (whatever sample), there is this bug:

<img width="1280" alt="Screen Shot 2022-03-24 at 13 08 47" src="https://user-images.githubusercontent.com/71526720/159960768-93b8fa95-3784-4f0a-a2c7-b9c063e2cefb.png">

**Comment by dkatsianos** [comment]
@kaiquemancoso these issues have resolved from previous issue. Can i close the issue?

**Comment by dkatsianos** [comment]
@kaiquemancoso these issues have resolved from previous issue. Can i close the issue?
