### ISSUE TITLE
[BUG] Form is not working on Figma input

### ISSUE THREAD

**Issue by kaiquemancoso** [Flutter-Vision/FlutterVision#58]
I'm trying to use this sample, but it is not working ("Invalid Application"). What is the problem? 

https://www.figma.com/file/Q7Fh2cEbTEZIoSaR6bbaIY/Sign-Up%2FLogin-Form-(Community)?node-id=1%3A76

**Comment by pattrickx** [comment]
The error occurred due to the two lines in the middle of the page, the back end does not support components with 0 in height or width.

![image](https://user-images.githubusercontent.com/32752004/160406122-00fa4998-37bf-4bd9-af35-dc35320bfe07.png)

**Comment by pattrickx** [comment]
@kaiquemancoso @teras I need a direction, on what we should do in relation to this element
