### ISSUE TITLE
[FEATURE] Retrieve Font Weight info from figma

### ISSUE THREAD

**Issue by reness0** [Flutter-Vision/FlutterVision#59]

**Comment by brunoamuniz** [comment]
I couldn't identify in the flutter code the weight of the font. Could you check?

<img width="956" alt="Screen Shot 2022-04-04 at 15 40 59" src="https://user-images.githubusercontent.com/3296036/161610264-a5a51d12-c897-4385-8478-cfb26627fe20.png">
[project.zip](https://github.com/Flutter-Vision/FlutterVision/files/8412299/project.zip)

**Comment by mateuslimax22** [comment]
@reness0 
The information is coming from the AI ​​but it doesn't arrive at the frontend
On AI:
![image](https://user-images.githubusercontent.com/38704964/161818372-57e5fbbc-cb9e-4d0e-a458-d51f504cf7a6.png)

On frontend:
![image](https://user-images.githubusercontent.com/38704964/161818186-462cd0df-565b-4a74-9753-2a59e5524b48.png)
