### ISSUE TITLE
[BUG] Error exporting to Flutter

### ISSUE THREAD

**Issue by brunoamuniz** [Flutter-Vision/FlutterVision#6]
## **Describe the bug**

20220316-15:29:26,/project/export/1/flutter/1080/1920,InvalidReferenceException: The following has evaluated to null or missing:
--
==> currentScreen.layout  [in template "flutter.ftl" at line 68, column 10]
 
----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression
----

**Comment by reness0** [comment]
provide me the project key and the figma token, pls

**Comment by reness0** [comment]
Fixed. Can u test it again @brunoamuniz?

**Comment by reness0** [comment]
@all-contributors please add @reness0 for code and maintenance
