### ISSUE TITLE
[BUG] When clicking on Export, it is taking too much time

### ISSUE THREAD

**Issue by kaiquemancoso** [Flutter-Vision/FlutterVision#63]
After clicking on Export, a rectangle appears and it looks like an error. Then, after waiting a while, the project is downloaded and survey modal opens. Can we fix this?

<img width="1280" alt="Screen Shot 2022-03-28 at 16 24 03" src="https://user-images.githubusercontent.com/71526720/160471870-d9b1b2aa-0455-4586-94c3-b82d50f49826.png">

**Comment by dkatsianos** [comment]
**Relative issue**

[FV not export when using screenshots #56](https://github.com/Flutter-Vision/FlutterVision/issues/56)  is the same bug
